project_id = "ezmughqpucdfuzldljtu"

[functions.paypal-subscription]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.fetch-remote-jobs]
verify_jwt = false

[functions.lookup-user]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
